### ISSUE TITLE
ints parameter not working 

### ISSUE THREAD

**Issue by artoriazz** [chicolucio/truth-table-generator#152]
I'm trying to display truth table with true/false instead of 0/1. Follow document, I add ints param and set it to False but look like its not working anymore.
print(ttg.Truths(sorted(toanhang), not_list + seperate_display +  stack, ints=False, ascending=True))
![image](https://user-images.githubusercontent.com/111276977/184610448-f208cf55-6fd8-423e-9a59-090ed232bdb4.png)

**Comment by zitotrex** [comment]
Fails: Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32                     
Succeeds: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]                                    

The following code fails in Version 3.10 and succeeds in Version 3.7, except for as_prettytable (failure is defined here as outputting 1s and 0s instead of Trues and Falses.
```python
import ttg
table = ttg.Truths(['p', 'q'], ['p = q'], ints=False)
print(table) # 1s and 0s
print(table.as_tabulate(index=False)) #1s and 0s
print(table.as_prettytable()) # True and False
```
Appears to be a bug after Python 3.7. I am too lazy to hunt this down any further, just use python 3.7 with ttg
Edit: I lied, I'm not lazy enough.
Went down in ttg.py and added a bunch of print calls, the bug must be happening in this call to tabulate, I checked the return value of as_pandas (return df) and it was still giving Trues and False, so the bug must be in the function that was calling as_pandas - which is tabulate
```
       p      q  p = q                                  
1   True   True   True                                  
2   True  False  False                                  
3  False   True  False                                  
4  False  False   True                                  
       p      q  p = q                                  
1   True   True   True                                  
2   True  False  False                                  
3  False   True  False                                  
4  False  False   True                                  
```
Portion of ttg.py, sorry that I don't follow a convention for citing error in code, I don't know any :D
```python
    def as_tabulate(self, index=True, table_format='psql', align='center'):
        """
        Returns table using tabulate package
        """
        table = tabulate(Truths.as_pandas(self),
                         headers='keys',
                         tablefmt=table_format,
                         showindex=index,
                         colalign=[align] * (len(Truths.as_pandas(self).columns) + index)  # NOQA long
                         )
        return table
```
