### ISSUE TITLE
Data extraction

### ISSUE THREAD

**Issue by jimmi19** [chicolucio/truth-table-generator#6]
Hi quick question how can I get data from the table? As an example I have:

`NgC = ttg.Truths(['A', 'B', 'C'], ['A and B or C'])` and I would like to extract the results column.

Thanks for any help with this. By the way nice scripts.

**Comment by chicolucio** [comment]
Hi! Sorry to take so long to reply.

You can extract the results using the `as_pandas` method in order to use all [pandas](https://pandas.pydata.org/) functionality.

With `NgC.as_pandas().iloc[:,-1].values` you will get: `array([1, 1, 1, 0, 1, 0, 1, 0], dtype=object)`

Let me explain: `iloc` is a pandas method. `iloc[:,-1]` means take all the lines (`:`) from the last column (`-1`) of the dataframe (created with `as_pandas()`). The `values` attribute is self-explanatory, without it a pandas series object will be the output instead. You can cast the array output to a list or any other type.
